# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches:
     - main
     - new-gh-action
  pull_request:
    branches:
     - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest #${{ matrix.os }}
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -el {0} # without this, conda env not active across steps

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
       auto-update-conda: true
       channels: conda-forge
       #activate-environment: Amuse-env
        #python-version: 3.13.3
    - name: Conda and env info
      run: |
        conda info
        conda env list
        git describe --long --dirty --always --tags
    - name: Install dependencies
      run: |
        conda install -y -c conda-forge pip wheel
        conda install -y -c conda-forge c-compiler cxx-compiler fortran-compiler 'gfortran<14' python pkgconfig coreutils patch curl tar unzip gzip bzip2 xz perl bison make cmake openmpi gsl fftw gmp mpfr hdf5 netcdf4 libopenblas liblapack zlib 'docutils>=0.6' 'mpi4py>=1.1.0' 'numpy>=1.2.2' 'h5py>=1.1.0'
        conda install -y pytest
        #conda install -y cuda
        ./setup
        conda list
    - name: Install amuse
      run: |
        ./setup install amuse-framework
        ./setup install ph4
        #./setup install sapporo_light ph4-sapporo
    - name: Run tests
      run: |
        echo $OMPI_MCA_btl_tcp_if_include
        export OMPI_MCA_btl_tcp_if_include=lo
        #./setup test ph4-sapporo
        ./setup test ph4

        #    - name: Install amuse
        #      run: |
        #        pip install -e .
        #        ./configure
        #
        #    - name: build AMUSE framework
        #      run: |
        #        make framework
        #
        #    - name: build SSE and BHTree
        #      run: |
        #        make sse.code bhtree.code
        #
        #    - name: check installation
        #      run: |
        #        amusifier --get-amuse-configmk
        #        pip list
        #
        #    - name: move build log
        #      run: |
        #        mv build.log build-${{ matrix.mpi }}-${{ matrix.python }}.log
        #    - name: archive build log
        #      uses: actions/upload-artifact@v4
        #      with:
        #          name: buildlog-${{ matrix.mpi }}-${{ matrix.python }}
        #          path: build-${{ matrix.mpi }}-${{ matrix.python }}.log
        #
        #    - name: test core_tests
        #      run: |
        #        pytest --pyargs amuse.test.suite.core_tests -s
        #
        #    - name: test compile_tests
        #      run: |
        #        ip link show
        #        echo $OMPI_MCA_btl_tcp_if_include
        #        pytest -k "not test29" --pyargs amuse.test.suite.compile_tests.test_c_implementation -sv
        #      env:
        #        OMPI_MCA_rmaps_base_oversubscribe: 1
        #        OMPI_MCA_btl_tcp_if_include: lo
        #
        #    - name: test code_tests
        #      run: |
        #        mpiexec -n 1 pytest --pyargs amuse.test.suite.codes_tests.test_bhtree -sv
        #        mpiexec -n 1 pytest --pyargs amuse.test.suite.codes_tests.test_sse -sv
        #      env:
        #        OMPI_MCA_rmaps_base_oversubscribe: 1
        #        OMPI_MCA_btl_tcp_if_include: lo
        #        OMPI_MCA_pmix_server_max_wait: 10
